### ISSUE TITLE
CustomRoom vs Room nodes

### ISSUE THREAD

**Issue by amvincentheapycom** [simonmoreau/DynamoMEP#2]
The Custom... nodes are breaking on me. Am I missing a new step to get these to function? 
![capture](https://cloud.githubusercontent.com/assets/24299492/20803188/554728de-b7bc-11e6-909d-325c6800abfb.JPG)

**Comment by ATPKMR** [comment]
I have the same problem, it "CustomRoom.FromElement" breaks if there are any "Nested Linked Models" in my Project.
Is there any solution for this Problem?

https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/Revit-Collaborate/files/GUID-F8929030-3D77-4F7B-A01F-3C88C600466E-htm.html
