### ISSUE TITLE
Check if the level is in the document

### ISSUE THREAD

**Issue by mitinrs** [simonmoreau/DynamoMEP#3]
//Check if the level is in the document
            if (level.InternalElement.Document != DocumentManager.Instance.CurrentDBDocument)
            {
                throw new ArgumentException("The level does not exist in the given document");
            }

Good afternoon. How can a level be equal to a document?

**Comment by mitinrs** [comment]
I understood. Level.InternalElement.Document returns the document to which the level belongs. But I have a mistake in 100%

**Comment by simonmoreau** [comment]
This feature is designed to prevent you from trying to create a space with a level coming from another linked project. If you are working on a single file, you should not have any issue with it.
